### ISSUE TITLE
`$set` doesn't apply immediately

### ISSUE THREAD

**Issue by daryl** [yyx990803/vue#1001]
I've noticed that when using `$set` after X amount of time it will not apply the changes until some kind of event happens (mousemove, etc.), whereas if I use it immediately the changes take place.

Do note that these examples are functions for the `created` property of a component:

```js
async function created() {
  let res = await post.feed(0);
  this.$set('items', res);
}
```

Another example:

```js
function created() {
  setTimeout(function() {
    this.$set('items', 'foo');
  }.bind(this), 2000);
}
```

Neither of these apply until I move my mouse across the page. What's the reasoning for this? It's not really ideal for a situation like this where I want to load in data asynchronously _within_ the component.

**Comment by yyx990803** [comment]
Can you provide a repro? It may have to do with the transpiler you are using...

**Comment by daryl** [comment]
I wanted to avoid making the repo public, so I made you a collaborator.

If it helps, I'm using Gulp and Babel.

The code in question is in `src/pages/feed/index.js`.

Watch: `gulp watch`
Run: `npm start`

**Comment by yyx990803** [comment]
Interestingly, here's what's causing this behavior: you are mounting the App instance to `body` with a string template. In 0.12.4+, the `replace` option is set to `true`, so the contents of your template replaces the `<body>` tag, which causes a Chrome-specific runtime error - which for some reason blocks re-rendering until a user interaction happens. The same code works properly in Firefox and Safari.

It can be fixed by simply giving your App a `replace: false` option, and I have added a warning in this particular case.

**Comment by yyx990803** [comment]
Also FIY, the code works in Chrome Canary too - it's a bug that is only present in the current stable version of Chrome.

**Comment by daryl** [comment]
Nice find, thanks for taking the time to find out.

**Comment by hay** [comment]
I've seen this problem as well, but on Safari (both mobile - 10.0 - and desktop - 9.1.3)

My code looks like this:

    setTimeout(function() {
        this.view.$set(this.view, 'loaded', true);
    }.bind(this), 2000);

The timeout does occur, but for some reason the `set` only happens occasionally. Frustratingly,that also means that i can't reliably repeat the bug. I see nothing weird in the console, except for some mixed-content warnings (HTTP / HTTPS), but i suppose those are not the culprit.

Same code works fine on Firefox and Chrome.
