### ISSUE TITLE
Different initial selected value in <select>

### ISSUE THREAD

**Issue by mbdavid** [yyx990803/vue#1008]
Hi, first of all, thanks for this fantastic work.

I note that `<select>` has a different behavior when using template from DOM element than `template` string options on `Vue` initialization.

When use template from DOM element, `Vue` render select with no value selected (v-model = null).

When using `template` from a string options, `Vue` render select with first value selected (v-model = null too).

![screenshot-jsfiddle net 2015-07-04 13-01-59](https://cloud.githubusercontent.com/assets/1137197/8508597/fe27b452-224c-11e5-95a0-3fcccd11dec2.png)

http://jsfiddle.net/8gv321no/

**Comment by yyx990803** [comment]
This is caused by some browsers' default behavior that whenever a `<select>` element is appended to a new parent, and its `selectedIndex` is `-1`, the browser resets it to `0`. It seems Firefox is the only browser that persists the `-1` value properly.

Ideally all browsers should persist the value, but I guess I can't change that so we can only add more ugly patches to Vue :(
