### ISSUE TITLE
Vue Broadcast inside multiple Components

### ISSUE THREAD

**Issue by SeoFood** [yyx990803/vue#1009]
How can I fire an event to trigger it in the component itself and in the same component but other scope.

Example: http://codepen.io/SeoFood/pen/WvzvJe

The broadcast event should increase both values, right? Or how can I fire an event to trigger both components?

**Comment by Nirazul** [comment]
`$emit` triggers only listeners in the same component, not on the same hierarchy level. To achieve this, the easiest way would be to use `$dispatch` or a callback prop hook, so that the parent is informed. And then trigger a `$broadcast` from within the parent.
With this approach, the sibling components stay decoupled from each other.

**Comment by yyx990803** [comment]
`$broadcast` only sends the event down to a component's descendants; `$dispatch` only sends it up the parent chain. There is no direct method to notify sibling components.

You can, as @Nirazul suggested, do a `$dispatch` -> `$broadcast` dance. Or, you can just use a standalone event emitter as a global event bus instead of relying on the component structure for event passing.

Also, please post questions like this to [vuejs/Discussion](https://github.com/vuejs/Discussion/issues). Issues here should be directly related to new features or bugs.
