### ISSUE TITLE
Watcher false triggering

### ISSUE THREAD

**Issue by miljan-aleksic** [yyx990803/vue#1014]
Here I am again, reporting another bug :)

When $watch is set on some deeper level and the root is altered the callback is triggered. This happens only when deep is On and the some new value is being added.

It's difficult to explain, so please check the [fiddle](http://jsfiddle.net/miljan/jjydxvyd). There the $watch should not be triggered as 'some' value is not changed, but it does. Same happens using this.$watch.

**Comment by azamat-sharapov** [comment]
I think `$add` is changing whole `$data` object, so watcher catches changes on `deep: true`. Because if you init property in you `$data` (which is recommended), [it won't happen](http://jsfiddle.net/jjydxvyd/1/), but yeah, sometimes we need to `$add` on the fly.

**Comment by miljan-aleksic** [comment]
Yes, sometimes when you are adding dynamic components that rely on the same main object. I can say that this behaviour is new introduced after 0.12 and changelog have no reference to it, so I assume is a bug.

**Comment by yyx990803** [comment]
It's actually not new. `$add`ing a root-level property always trigger a full digest for all watchers, this is because if a watcher is watching a non-existent property, it would have caught no dependencies on initialization, and there's no way to notify it unless we do a full digest. This is also why I strongly recommend against `$add`ing root level properties on the fly.

**Comment by azamat-sharapov** [comment]
This is useful info, Evan, didn't know about this. Should probably be added somewhere in docs..

**Comment by miljan-aleksic** [comment]
Thanks for looking into this Evan, maybe I'm getting confused but I'm not watching a non-existing property. Eg ```{someData: {my-value: 89}}```

I start watching changes for 'my-value', with ```$.watch('data.my-value', {}, deep: true)```. Then I add another root level value with ```$add('someData', {})``` and the object become ```{someData: {my-value: 89}, moreData{}}```. I would expect my watch be exclusively triggered if some of the 'my-value' data is changed. But seems I'm wrong?

**Comment by yyx990803** [comment]
Yeah, adding a root level property triggers a re-evaluation of **all** watchers in that component. For normal watchers, if the previous value and the new value didn't change, the callback is not triggered; but deep watchers would trigger even if the value was the same (because it could be the same object but mutated). Maybe in this case the digest could be "shallow", i.e. only calls the callback when the value has changed.

**Comment by miljan-aleksic** [comment]
The "shallow" option sounds good, because for deeper level watchers it doesn't matter if the object has mutated or not, the only what matter if the watched value has changed. I don't mind if its a default behaviour or optional, but I would keep it always On in my code :)

**Comment by miljan-aleksic** [comment]
Thanks Evan :)
