### ISSUE TITLE
Vue can't observe object prototype chain

### ISSUE THREAD

**Issue by karevn** [yyx990803/vue#1024]
If I pass an Coffeescript class instance as Vue's data, the properties those belong to the prototype can't be watched. As far as  I understand, it's because Observer enumerates properties using Object.keys, call, which does not respect prototype chain. How about using for (key in obj) instead? My quick test shown it does not break Vue. And I can submit a patch if you want.

**Comment by karevn** [comment]
Basically, here is what happens:

    a = {b: 1}

is observed with no problems. But when I use this code:

    class Klass
      constructor: -> @b = 1
      a: 2

then "b" is observed fine, but "a" is not, so the next code will not work 100% as expected:

    new Vue(
      data: -> {instance: new Klass}
    )

**Comment by yyx990803** [comment]
This is by design. Two reasons:

1. Data objects need to be persistable and inspectable via `JSON.stringify()`, which also ignores prototype properties.

2. When we observe a prototype property, we are adding an own property getter to the object that shadows the prototype property, so there will no longer be dynamic prototype chain lookups. If the prototype is mutated the change won't be reflected in the observed object.

If you want a property to be observed, make it an instance property instead of a prototype property.

**Comment by karevn** [comment]
Hmm... okay. I thought a little bit, and it looks like the current design is optimal. I can make my model's methods prototype properties (to be ignored by vue), and use watched instance properties.
