### ISSUE TITLE
The old and newVal on the watch doesn't seem to be working as expected.

### ISSUE THREAD

**Issue by abishekrsrikaanth** [yyx990803/vue#1086]
I have here 2 jsbin's with the watch function enabled that doesn't seem to be working as expected.

http://jsbin.com/cenepog/edit?html,js,console,output - Example with Watch options
http://jsbin.com/fekire/edit?html,js,console,output - Plain Watch Example

Both the above example seems to produce the output 

```
"Changes Noticed -> New Val :1,2,,4, Old Val: 1,2,,4"
"Changes Noticed -> New Val :1,2,5,4, Old Val: 1,2,5,4"
```

Not quite sure if I am wrong anywhere..

**Comment by yyx990803** [comment]
That's expected behavior. `newVal` and `oldVal` for reference type values (Arrays and Objects) **will be the same** if it is just mutated rather than replaced entirely. Vue doesn't (and doesn't need to) cache a deep copy of the value like Angular does. Even if it gives you different values, you'd still need to diff the arrays yourself to do anything useful.

What are you trying to achieve with the old value?

**Comment by abishekrsrikaanth** [comment]
@yyx990803. Your exaplaination makes sense, but has this changed recently or was this the case since the beginning?

**Comment by yyx990803** [comment]
This has always been the case.

**Comment by abishekrsrikaanth** [comment]
@yyx990803 OK, thnx
