### ISSUE TITLE
children calling $root's methods is not reactive

### ISSUE THREAD

**Issue by nkovacs** [yyx990803/vue#1114]
I wanted to build an i18n system that can update the entire app when you change the language.
So the idea was to have a root vm that holds the current language (actually a [globalize](https://github.com/jquery/globalize) object), a method to change the language and the translation method. The problem is, without inherit: true, child components don't get these methods in their scope. I didn't want to add inherit:true to every component, so I tried to write a mixin that defines these methods on every component I need, and then forwards them to the root vm.

Here's a simplified version of it: <s>http://jsfiddle.net/nkovacs/gb0vg75a/</s>
edit: the child components were not actually children in the testcase, fixed: http://jsfiddle.net/nkovacs/gb0vg75a/5/

This works, except the children are not updated when you change the language.

I also looked at [vue-i18n](https://github.com/kazupon/vue-i18n), which uses Vue.prototype to add a $t method to everything, but I think you'd run into the same issue if you tried to make it reactive like that.

I came up with a different solution that does work: http://jsfiddle.net/nkovacs/1zh3agxr/
Is that ok, or is there a better way to do it?

**Comment by davidkhess** [comment]
Wouldn't this be a perfect use case for $broadcast'ing an event at the $root that all View Models would listen and react to?

**Comment by nkovacs** [comment]
But how do you update the bindings?

**Comment by davidkhess** [comment]
Since a picture is worth a thousand words, here's what I would do:

http://jsfiddle.net/gb0vg75a/3/

**Comment by nkovacs** [comment]
Yeah, I though of using broadcast like that, but I didn't want to inject the globalize object into each vm.

I prefer my solution (http://jsfiddle.net/nkovacs/1zh3agxr/ or http://jsfiddle.net/nkovacs/1zh3agxr/2/ or http://jsfiddle.net/nkovacs/1zh3agxr/3/) because the private data (the translator object) is kept away from the vms.

The plugin/mixin essentially becomes a service that's injected into the vm (either automatically into all vms if it's a plugin or manually if it's a mixin), and it exports some functions (its public API essentially) while keeping the private data separated.

**Comment by davidkhess** [comment]
Note, the way you are using `new Vue` is not creating children View Models of the body tag Vue. See this fiddle where I added some logging to make that clear:

http://jsfiddle.net/1zh3agxr/4/

The best way to get parent child relationships like that working is to use the component system.

**Comment by nkovacs** [comment]
Oh, that's confusing. Thanks for pointing that out. But even if I fix that, it doesn't work: http://jsfiddle.net/nkovacs/gb0vg75a/5/
In the real app it's actually a dynamic component: http://jsfiddle.net/nkovacs/gb0vg75a/6/

**Comment by davidkhess** [comment]
Two problems. First, your `data` functions in the components should have been returning `{}` and were not. But the second and key problem is that in order to bind to `translator` you need to make sure that the Vue has it defined in its `data`. Otherwise, when Vue binds the `t()` calls, it will not see the reference to translator and therefore can't watch it – which causes them to not update when `translator` is created and updated later.

http://jsfiddle.net/gb0vg75a/8/

**Comment by nkovacs** [comment]
You're right, but I was using this.$add, and that works when it's on the same component, even though translator isn't defined on the root either, but it does not work on the children.

**Comment by davidkhess** [comment]
My understanding is that `$set` and `$add` deal with setting up data for components and directives that are compiled after they are executed – I don't think they effect anything already compiled in the DOM before that point.

Maybe @yyx990803 could shed some light on that subtlety?

**Comment by yyx990803** [comment]
This is another reason why you should prefer initializing the data properly. A working verison: http://jsfiddle.net/yyx990803/gb0vg75a/11/

Internally, calling `$add` on a vm causes all its watchers to be re-evaluated, because this is a new dependency that non of the existing watchers are aware of. This is essentially a forced dirty-check digest cycle like in Angular, and it only propagates to a child if a child has `inherit: true` (because normal components should derive parent data via `props`, which are also force-updated during the digest cycle).
