### ISSUE TITLE
I think v-change (like `ng-change` of AngularJS) is needed in Vue. How do you think about this?

### ISSUE THREAD

**Issue by endaaman** [yyx990803/vue#1159]
I implemented `v-change` in [my repo](https://github.com/endaaman/vue/tree/v-change). It can be used in the following codes.

```html
<input v-change="change($value)">
```
```js
new Vue({
  ....
  methods: {
    change: function (v) {
      console.log(v)
    }
  }
})
```
`$value` is available like `$event` of `v-on`.

When we want to just detect only changes, even if we don't need basically to define a model we need to define a model purposely and use `$watch` or `computed property`. So I think that such like `v-change` directive is needed in Vue.

I wrote an [article](http://qiita.com/endaaman/items/2ee6f76926c069c84793) (sorry, it is written in Japanese) and tweet this, then I was said `nice one` by @yyx990803 on twitter(https://twitter.com/youyuxi/status/631609400692752384).

How do you think about this? If you agree with my opinion, I will make a PR(already ready to do).

**Comment by JosephSilber** [comment]
Why not simply:

<input v-on="change: onChange($event.target.vale)">

**Comment by yyx990803** [comment]
@endaaman Thanks for the suggestion. I'm sorry because I probably misunderstood some points in your article when I was reading it (I used Google translate). I thought there was a problem when using `v-on` together with `v-model` (e.g. you are getting wrong model value inside `v-on` listeners), but it seems that's not the case.

As @JosephSilber suggested, if you are not using `v-model`, you can simply use `$event.target.value` inside your `v-on` expressions.

I'm sorry for suggesting you to open a PR due to the misunderstanding, but your directive is still nice work.

--
P.S. `$value` is a reserved meta property inside `v-repeat`, so you may want to pick a different name to store the value.
