### ISSUE TITLE
Using HTML tags in strings inside mustache braces

### ISSUE THREAD

**Issue by plashenkov** [yyx990803/vue#1186]
For some reason using HTML tags in strings inside triple mustache doesn’t work as expected.
Example:

```js
{{{ item.price_for == 'item' ? 'items' : 'm<sup>2</sup>' }}}
```

In this case it will output to HTML everything including triple braces.

P.S. For double mustache it has the same issue.

**Comment by yyx990803** [comment]
Note Vue templates are parsed as actual HTML. The `<sup>` tag in your template is parsed as an actual tag and breaks up your expression. As a rule of thumb, you should never include tags inside mustache expressions, because Vue is **not** a string-based template language. Use either a filter or a computed property for this case.

**Comment by GuoerJS** [comment]
@yyx990803  小右哥，请教一个问题：我想在数据库的某个字段中插入一个html tag，像这样:"今日流量:<br/> 888"，然后这个字段在页面里通过vue渲染出来的，但是在页面里并不会像我期待的那样换行，而是原封不动的渲染出来字符串。我该怎么做呢？
