### ISSUE TITLE
Can't I use "footer" as a vue-component's name ?

### ISSUE THREAD

**Issue by HustLiuCN** [yyx990803/vue#1323]
as the title says.
I found when I set "footer" a component's name like: 
```javascript
new Vue({
  // other code here
  components: {
    footer: {template: "..."}  // if I change "footer" into other name like "foot" , all goes well
  }
}
  // other code here
```
It will throw an error **"Uncaught RangeError: Maximum call stack size exceeded"**, I wonder what mistake I've made ~

**Comment by azamat-sharapov** [comment]
Yes, you can't use standard HTML tag names as component names.

**Comment by HustLiuCN** [comment]
thx a lot :D

**Comment by yyx990803** [comment]
There will be warning for common HTML5 elements in the future.
Basically when you use `<footer>` inside `<footer>` it's like a self-recursive call that never ends, but Vue needs to support self-recursive components for e.g. file tree components.

**Comment by reed1** [comment]
I got this issue too, but instead of recursive call, Vue just didn't render the element

```javascript

import Vue = require('vue');

Vue.component('header', '<div>Header Component</div>')

new Vue({
  el: '#app',
  template: '<header></header>',
  data: {}
});
```

I think it's good to warn user that HTML5 elements are not allowed. I can open a PR by using [commonTagRE](https://github.com/vuejs/vue/blob/bd6b22517595af7756d4e8b755582f60f4ad156a/src/util/component.js#L12) to trigger warn but I don't know much about Vue internals, probably that's not the best idea,

thanks,
-reed1

**Comment by yyx990803** [comment]
@reed1 it does warn for component options. Added warning for global registration as well.
