### ISSUE TITLE
Assigning computed property through code doesn't invoke it's setter.

### ISSUE THREAD

**Issue by huestack** [yyx990803/vue#1360]
I am binding a template with list, and items are listed as expected in &lt;li&gt; tags. The problem is computed property: selected. The setter of this property is triggered when the checkbox is clicked, however, if the property is set in code, the setter isn't called.

When "Start Selection" button is hit, checkboxes are visible for each item. When user clicks on checkbox, setter of computed selected property is invoked. However, if you press, "Select All" button, which sets selected property to true, checkboxes are visible, and they are duly checked, but setter of selected property isn't triggered, which is unexpected. Why isn't this working? Either I am missing something, or this is a bug in Vuejs.

Here is a link to fiddle: http://jsfiddle.net/dreamakshay/c76rwugz/5/. These are few things you can try.

Run > Click Start Selection > Tick Checkboxes (setter triggered) > Message in Div, and "Remove" will remove the selected items.

Run > Click Select All (all checked) > Press Remove > An unexpected error in Div "Nothing to remove", which shouldn't happen.

Any help is appreciated.

**Comment by yyx990803** [comment]
There are many problems in your fiddle.

1. Computed properties are only exposed on the **component instance**, not the original data. In your fiddle you are setting `selected` to true on the raw data object in `list`, not the actual component instances. You need to use `v-ref="list"` on the `v-repeat` list so that you can access the component instances as `this.$.list`.

2. I don't know why you are calling `$add` on the parent `selectedList`. Please read [this section](http://vuejs.org/guide/best-practices.html#Adding_and_Deleting_Properties) carefully and make sure you understand what each method does. Also, if you pass a number to `arr.$remove()`, it will assume it's an index and remove the item at that index, so you need to use native methods like `indexOf` and `splice` to do the removal.

3. In your `selected` getter, you should check `index > -1` rather than `index > 0`.

Fixed fiddle: http://vuejs.org/guide/best-practices.html#Adding_and_Deleting_Properties

**Comment by huestack** [comment]
Thanks, Evan, for your reply.

1. It seems I have misunderstood Components. Well, following your suggestion, my code worked like a charm.
2. At first, I was using `push` and `splice` methods, but since it didn't work somehow, I used `$add`, and `$remove` methods. But now `push` and `splice` methods are working.
3. Original code does have `index > -1`.

Thank you for guiding in right direction.

Ritesh
