### ISSUE TITLE
Latest binding syntax + .vue + webpack compatibility issue

### ISSUE THREAD

**Issue by karevn** [yyx990803/vue#1380]
I am not sure where it's best to post this one, but here this code:

```vue
<template>
<img :src="property">
<img v-bind:src="property">
</template>
```
breaks webpack loader with the next error:

```
Module not found: Error: Cannot resolve 'file' or 'directory' ./property in ...
```

```vue
<template>
<img :src.sync="property" >
</template>
```
compiles fine (but is incorrect, I know).

The deal is definitely in the way `src` attr is handled in Webpack. 

Ideas?

**Comment by karevn** [comment]
Hmm. I found the problem: https://github.com/webpack/html-loader/pull/30

But it can be larger than that - who knows which other parsers will not like ":" char in attribute names.

**Comment by yyx990803** [comment]
@karevn that means it's a crappy parser. `:` is a valid HTML attribute char.

**Comment by karevn** [comment]
@yyx990803 very constructive...

**Comment by yyx990803** [comment]
@karevn the current syntax can be correctly parsed in all supported browser down to IE9, and the most commonly used Node.js parsers like `parse5` or `htmlparser2`. If a parser is implemented correctly according to the HTML spec, then it should be able to handle the syntax. `html-loader` is an unfortunate case where there happens to be a not-so-standard-compliant parser in the toolchain, but it can be fixed.

I don't any reason to change Vue's syntax just because someone could happen to write a non standard-compliant HTML parser.

**Comment by karevn** [comment]
I did not tell anything about changing the syntax (at least here). It would be more pragmatic not to become defensive, but to think about more comprehensive testing against a surrounding ecosystem to make sure Vue works fine with other tools.

**Comment by yyx990803** [comment]
I apologize if i sound defensive, but opening an issue here implies that
you think something should be done in Vue core to address the problem. If
there's nothing to do with Vue core, you should've opened the issue at
vue-loader or directly at html-loader instead.

**Comment by karevn** [comment]
As we see, I figured and fixed the problem myself (and it's in an another project code actually). But still - I think it worths to re-test Vue against all the surrounding frameworks (webpack, browserify, etc before 1.0 release). Just as a preventive action.

**Comment by yyx990803** [comment]
Sure, that's the point of beta

**Comment by jumplee** [comment]
@karevn  +1 
save my Life for updating vue....
