### ISSUE TITLE
v-show on a component does not work when its template is just another component

### ISSUE THREAD

**Issue by taras-puchko** [yyx990803/vue#1388]
Please see http://jsfiddle.net/5sH6A/176/

**Comment by Mat-Moo** [comment]
v-show works on dom elements, you're replacing it so it can't use display none etc. Try v-if instead.

**Comment by taras-puchko** [comment]
I'm replacing DOM [here](http://jsfiddle.net/5sH6A/177/) too, but it works in that case.

**Comment by yyx990803** [comment]
A component that contains just another component makes the parent component a [fragment instance](http://vuejs.org/guide/best-practices.html#Fragment_Instance), because the two components cannot share the same root node.

In general you should avoid components that only contain another component - why would you do that in the first place?

**Comment by taras-puchko** [comment]
I have several object types that are displayed in a similar way. So my inner component handles presentation and several outer ones contain business logic specific for a particular type of object and pass data to the inner component instance.

**Comment by yyx990803** [comment]
I'll add warning for this case in a future release. A simple solution is wrap your component with an outer element:

``` html
<div v-show="condition">
  <your-component></your-component>
</div>
```

Or use `v-if` instead.
