### ISSUE TITLE
<slot> inside a v-for inside a <table> doesn't get repeated

### ISSUE THREAD

**Issue by thelinuxlich** [yyx990803/vue#1395]
Will add the element once

**Comment by thelinuxlich** [comment]
Actually this is happening only with tables:

http://jsfiddle.net/hdpgrxp4/6/

**Comment by yyx990803** [comment]
Hmm this is similar to custom elements inside tables because `<table>` only allow certain elements inside it. I guess we need to implement something like `<tr is="slot">` for this.

**Comment by thelinuxlich** [comment]
:+1:

**Comment by yyx990803** [comment]
Turns out even if we implement `is="slot"`, it is still quite awkward to use slots with table elements, because in the parent template, you cannot directly render table elements:

``` html
<comp>
  <td>123</td>
</comp>
```

Gets rendered as:

``` html
<comp>
  123
</comp>
```

Basically, because table elements cannot appear "naked", they are ignored before the content transclusion even starts.

The suggestion is always transclude non-table elements, and use `<slot>` inside `<td>` instead: http://jsfiddle.net/yyx990803/hdpgrxp4/9/

**Comment by thelinuxlich** [comment]
Hmm interesting, so it is impossible to insert headers and columns on the fly
