### ISSUE TITLE
CSS class bindings break unexpectedly

### ISSUE THREAD

**Issue by thebearingedge** [yyx990803/vue#1425]
Hello,

With `1.0.0-beta.4` I ran into a problem using a custom single-mustache config.

```javascript
Vue.config.delimiters = ['{', '}']
```
Everything I've tried so far has worked well. Vue is quite nice to work with!

But this template breaks until I revert back to the double-mustache config:
```html
<ul>
  <li v-for="item in items"
    :class="{ 'is-first': $index == 0 }">{ item }</li>
</ul>
```
`Uncaught TypeError: Cannot read property 'get' of undefined`

I made a fiddle that demonstrates the problem [here](https://jsfiddle.net/thebearingedge/02yar92z/1/).
Thanks so much, please let me know if there is anything else I can do.

**Update:**

This may actually be an issue with `:class` bindings themselves. Even with default delimiters, the same error occurs:
```html
<li v-for="item in items" :class="'is-first': $index == 0">{{ item }}</li>
```

**Comment by yyx990803** [comment]
The first issue is because you've set the delimiter to something that is ambiguous inside valid JavaScript expressions. It's difficult to differentiate between an interpolation tag vs. object literal, both for users and Vue's parser. I recommend using something that's more obvious, e.g. `['${', '}']`.

The code in the update section is now invalid syntax - all directives expect a single valid JavaScript expression now.

**Comment by thebearingedge** [comment]
I'm okay with this :+1:
