### ISSUE TITLE
Dispatching input/change events on model changes

### ISSUE THREAD

**Issue by aristidesfl** [yyx990803/vue#503]
Does Vue send input/change events when it modifies the UI to reflect the model?
This could be useful for 3rth party UI plugins to know when to update..

**Comment by aristidesfl** [comment]
One other example where events would be useful: http://jsfiddle.net/xg9oaddb/2/
If you see a more elegant way to do this please let me know.
Thank you!

**Comment by bdaglish** [comment]
You don't need events for that - just v-style ... http://jsfiddle.net/bdaglish/xg9oaddb/4/  .

**Comment by aristidesfl** [comment]
@bdaglish great answer! so much simpler!
With a slight modification so it can be used in other sliders too: http://jsfiddle.net/xg9oaddb/5/

**Comment by swernerx** [comment]
I'm not happy with the solution provided here which effectively just say: Don't use 3rd-party solutions at all. I do want the same: a fully custom range slider. My current set-up works for updating the model value via the custom slider component, but not the other way around. Any changes to the model data are not reflected to the custom component.

This is because the connected input field of the component does not fire any user DOM events e.g. input/change when the data is modified programmatically by VueJS. In my opinion there should be some work around for this. Effectively this not only affects sliders but all custom non HTML5 standard input methods which can't be easily styled via CSS. Things like rangeslider.js or material design light.

**Comment by swernerx** [comment]
Here is my work-around using 'watch' + manual model updates. 

Usage in view/template:

```html
  <range-slider id="input-invest-horizon-new" :min="1" :max="25" :value="contribution.investmentHorizon" v-on:change="saveHorizon">
  </range-slider>
```

Custom component implementation:

```js
import Vue from 'vue';
import $ from 'jquery';
import rangeslider from 'rangeslider.js';

const RangeSlider = Vue.extend({
  template: '<input type="range" min="{{min}}" max="{{max}}" v-model="value">',

  // This connects the DOM attributes from the template to the programmatic values
  props: {
    value : {
      type: Number,
      twoWay : true
    },

    min : {
      type: Number
    },

    max : {
      type: Number
    }
  },

  watch : {
    value : function(value) {
      $(this.$el).rangeslider('update', true, true);
      this.$dispatch('change', value);
    }
  },

  ready: function() {
    $(this.$el).rangeslider({polyfill : false});
  }
});

Vue.component('range-slider', RangeSlider);

export default RangeSlider;
```

Parent view:

```js
import Vue from 'vue';

export default Vue.extend({
  ...
  methods: {
    saveHorizon: function(value) {
      this.contribution.investmentHorizon = value;
    }
  }
});
```

I figure it would be nicer to solve this more declarative in HTML/template syntax instead of custom event listener/setting properties (which is repeated for every single view using the slider component).

**Comment by swernerx** [comment]
BTW: It would be probably interesting for watchers to know about the origin of the change (e.g. inside/outside for two-way binding).

**Comment by swernerx** [comment]
To clarify. What I am looking for is something like:

```html
  <range-slider id="input-invest-horizon-new" :min="1" :max="25" 
    v-model="contribution.investmentHorizon">
  </range-slider>
```

which reads/write like for normal input fields to the model defined in the attribute value.

**Comment by djam90** [comment]
+1 I also need this functionality. When Vue updates the DOM value it should fire change/input so that other libraries can work with it.

**Comment by hirenkeraliya** [comment]
If i use third party plugin for slider like jequery slider. and use the component to make slider then how to get the value of the slider.....
1)  slider text box is in the component
2)  get the value of slider onchange in normal but in component can not trigger that.
How to make this????
Thanks ....
