### ISSUE TITLE
Getting "TypeError: node is undefined" when compiling my Vue component

### ISSUE THREAD

**Issue by TMiguelT** [yyx990803/vue#643]
So here's a JS fiddle that replicates the issue: http://jsfiddle.net/v98rskqt/. Basically I'm trying to make a Vue component to use as a bootstrap modal.

I suspect I've done something in my JS that's caused this error in the compilation, but even if it is my fault, could this situation have a relevant Vue error message to help users?

```javascript
var vm = new Vue({
    el: "#parent",
	components:{
		"m-modal": {
			paramAttributes: ["show"],
			template: "#partial-modal",
			data: function () {
				return {
					_show: false
				};
			},
			computed: {
				show: {
					get: function () {
						return this._show;
					},
					set: function (val) {
						this._show = val;
						if (val)
							$(this.$el).modal("show");
						else
							$(this.$el).modal("hide");
					}
				}
			},
			replace: true
		}
	}
});
```

**Comment by yyx990803** [comment]
The root cause of this issue is because the computed setter for `show` is triggered during the compilation phase - which means the DOM was altered during compilation so the linker cannot work properly. As @brandonjpierce pointed out, it's not recommended to perform DOM manipulations in computed setters - what you want can be achieved by simply using watchers instead: http://jsfiddle.net/v98rskqt/1/
