### ISSUE TITLE
any reason for missing v-prop directive?

### ISSUE THREAD

**Issue by normanzb** [yyx990803/vue#644]
a builtin v-prop would be very convenient for modifying dom properties such as scrollTop?

**Comment by yyx990803** [comment]
So after going through the list of settable properties on a DOM Node/Element, it seems the actual usage for a dedicated `v-prop` directive is... pretty rare. `scrollTop` is probably the only meaningful use case (since most others can be covered by `v-attr`). In the cases where it's needed, it's also trivial to write a custom directive, so we'll leave `v-prop` out.
