### ISSUE TITLE
subscribers is undefine

### ISSUE THREAD

**Issue by Joeyfish** [yyx990803/vue#654]
Vue version 0.11.4

encounter below error :
vue.js:4467 Uncaught TypeError: Cannot read property 'update' of undefined vue.js:4467 
p.notify vue.js:6958 
Object.defineProperty.setvue.js:1489 
proxySetterrecordMainPage.js:49 
Vue.component.methods.onRecordChangevue.js:1894 
(anonymous function)VM58885:3 
(anonymous function)vue.js:4622 
handler vue.js:3415 
handler

it happens only once. if click other dropdown it works as well.

if jsfiddle example needed, i will extract one.

**Comment by xhinking** [comment]
Please append a jsfiddle example.

**Comment by Joeyfish** [comment]
Duplicate with issue#678. closed.

**Comment by jcoffland** [comment]
I'm seeing this same problem.  It's not exactly the same as #678 but is likely related.  What I notice is that in this loop from vue.js:

	p.notify = function () {
	  for (var i = 0, l = this.subs.length; i < l; i++) {
	    this.subs[i].update()
	  }
	}

```i``` can be greater or equal to ```this.subs.length```.  What I think it happening calls to ```update()``` can modify ```this.subs```.  In other words, events can cause event listeners to be added or removed.  For example, if an event affects a scoped variable, then components may be detached.  I was able to work around this by using ```v-show``` instead of ```v-if``` in places where an event could affect the value.
