### ISSUE TITLE
Child Components

### ISSUE THREAD

**Issue by triplekdev** [yyx990803/vue#661]
Hi @yyx990803 

Is there an easy or dynamic way in adding a VueComponent to a "some components " `.$` ? also A way to assign a VueComponent to a variable; see below `(1)`

    var myComponents = {};

    myComponents.NavBar = Vue.component(...)

    // later
    myComponents.NavBar.[some.data.variables] = [some value]

and for the previous query of child components `(2)`:

    Vue.component('ui-navmenus', {
        parent: 'ui-nav'
        ...
    });

    // later
    MainApp.$['ui-nav'].$.['ui-navmenus']

if ever `1` is possible, `2` would not be needed somehow because of just accessing the variable assigned.  Or do you have other way of accessing the child? 

Thanks!

**Comment by TMiguelT** [comment]
I think both of these questions are coming from your confusion about components. As the [guide](vuejs.org/guide/components.html) says, 
>Vue.component() ... is an asset registration method 

What this means is that `Vue.component("navbar", {...})` *does not* return a navbar component that you can store and manipulate, but rather defines how navbar components should be created.  To actually instantiate the component, you need to use it somewhere in your HTML template.  The guide mentions a few ways to do this. You can use the v-component directive like this:
```html
<div v-component="navbar"></div>
```
Or you can use the component name as the tag name like this:
```html
<navbar></navbar> 
```
What this will do is use create a component at this location in the DOM. If you're used to classical inheritance, `Vue.component` is like defining a *class*, while using `v-component` is like instantiating that class.

Now to address your questions, the $ property of a Vue instance *is* automatically populated with child components, you just have to instantiate them in the HTML along with the [`v-ref`](http://vuejs.org/api/directives.html#v-ref) directive like this:
```html
<div v-component="navbar" v-ref="ui-nav"></div>
```
```javascript
var vm = new Vue({...});
var ui_nav = vm.$["ui-nav"];
```
You could then modify the ui_nav component by accessing its properties if you wanted. However if you're modifying the data of a child object, it's often better to do so using the [event system](http://vuejs.org/guide/components.html#Event_System), because this *decouples* your components from each other, allowing them to be re-used and modified with a lot less difficulty. For example, what happens if you put the ui_nav component inside another component? Now you'd have to change *all* your code that accesses the child component because it's now another level down the component chain.

**Comment by builtap** [comment]
From the documentation (http://vuejs.org/api/directives.html#v-ref): v-ref... "Registers a reference to a child component on its parent for easier access". This will not add a child component to a parent VM. 

From the documentation (http://vuejs.org/api/instance-methods.html#vm-\$add\%28_keypath\,_value_\%29): "Due to the limitations of ES5, Vue cannot detect properties directly added to or deleted from an Object". Therefore, it is expected that adding/removing references to the vm.$ object is done via vm.$.$add(), vm.$.$delete().

Following the documentation (http://vuejs.org/api/global-api.html#Vue-extend\%28_options_\%29) here's one way to add components dynamically to a parent VM, as well as creating 'v-ref's for them:

```html
<body><div id="someNode"></div></body>
```
```javascript
/* create root VM */
var vm = new Vue({el:'body'});

/* create class/type Profile, AFTER root VM is attached, per desired dynamic behavior */
var Profile = Vue.extend({
    name:'profile-component',
    el: function () {
        return document.createElement('p');
    },
    template: '{{firstName}} {{lastName}} aka {{alias}}'
});
/* create instances of type Profile */
var c1 = new Profile({
    data: {firstName:'Edward', lastName:'Snowden', alias: 'Citizen 4'},
}).$appendTo(document.querySelector('#someNode'));

var c2 = new Profile({
    data: {firstName:'Anne', lastName:'Frank', alias: '~A-25060'}
}).$appendTo(document.querySelector('#someNode'));

/* add to .$ */
vm.$.$add('c1',c1);
vm.$.$add('c2',c2);

/* access components via reference directly: */
console.log(vm.$.c1);
```
Therefore, the following might not be useful:
```javascript
... NavBar.[some.data.variables] = [some value]
```
Instead, use some of the framework provided api such as $set, $add, $delete.

**Comment by triplekdev** [comment]
@TMiguelT and @builtap Thanks guys.. the reason I am doing this is to make something like a library of Component for a frontend I am making, something like a common admin cp type of applications, that has a lot of components that can be added and such.. I admit some documentations with vuejs are so far very basic and some sample application uses the vue-loader which i am only using plain javascript.. Thanks again for the pointers, appreciated it and happy new year!
