### ISSUE TITLE
New Option `name` preventing Vue 0.10.x -> 0.11.x upgrade

### ISSUE THREAD

**Issue by jordangarcia** [yyx990803/vue#676]
We are in the process of upgrading our codebase to using Vue 0.11.4 and have run into several issues regarding the automatic conversion of a component id or child component key into a function constructor name.

Our registry of components looks like:

```js
module.exports = {
  'butterbar': require('componts/butterbar'),
  'dialogs/alert': require('componts/dialogs/alert'),
  // ...
}
```
This map gets sent iterated over and calls `Vue.component(id, component)`

Vue seems to want to try to coerce the `id` into a function name using the `camelize` function which does not support forward slashes and ostensibly other characters that are valid id's but not valid function names.

This is a really blocking issue for us.  In the mean time we will have to fork Vue to allow the upgrade to happen in the timeframe we've allotted.  In my opinion this conversion of id to function constructor name is too much magic for what is essentially a debugging feature.

Thanks!

**Comment by TMiguelT** [comment]
The issue isn't the `camelize` function, I believe the issue is that Vue dynamically creates a constructor function using the camelized name:
```javascript
function createClass (name) {
  return new Function(
	'return function ' + _.camelize(name, true) +
	' (options) { this._init(options) }'
  )()
}
```
So inherently the name variable has to be a valid javascript identifier, which it is not if it has slashes, and camelize ignores slashes. I can see this being annoying, and we'll see what @yyx990803 thinks about it, but I believe the recommended way of "namespacing" your components is to use hyphens, because then they will camelize correctly, and will also be able to be used directly in html as:
```html
<dialogs-alert></dialogs-alert>
```
So you may be working against the library to some extent.

**Comment by agonbina** [comment]
I also think it's generally recommended to use hyphens in the component identifier when dealing with web components. For example in Polymer it is *required* that you use a ```-``` for the [```name```](https://www.polymer-project.org/docs/polymer/polymer.html#attributes) attribute of a component

**Comment by yyx990803** [comment]
Component names with slashes are now supported as in 8a02eb1.
