### ISSUE TITLE
<content> tag may not be enough to serve as insertion points in <table>

### ISSUE THREAD

**Issue by Gerhut** [yyx990803/vue#692]
I am writing a component of `<table>` & `<td>`

When Vue compile my template `<table><tbody><tr><content></content></tr></tbody></table>`

After compiled, we saw that `<content>` tag moved outside the `<table>`
![image](https://cloud.githubusercontent.com/assets/2500247/5915870/bbecda3c-a645-11e4-8a96-54677be1c60d.png)

My opinion is add `content` attribute as well as tag name to serve as insertion points
![image](https://cloud.githubusercontent.com/assets/2500247/5915897/0331cef2-a646-11e4-802d-649c0e139f4f.png)

Or `? _.toArray(el.querySelectorAll('content, [content]'))` at [transclude.js#L126](https://github.com/yyx990803/vue/blob/master/src/compiler/transclude.js#L126)

Sorry for my poor English.

**Comment by Blitz2145** [comment]
This problem bit me today, `content` as an attr would work.

**Comment by yyx990803** [comment]
Sorry for the late reply on this. Turns out `content` as attr would not completely solve this problem, because say when you have the markup:

``` html
<div v-component="my-table">
  <td>{{test}}</td>
</div>
```

Since `td` is not allowed inside `div`, the browser will throw it away and end up with an empty `div`. Nothing will be trancluded;

If you do this:

``` html
<table v-component="my-table">
  <td>{{test}}</td>
</table>
```

Since `td` is not supposed to be nested directly under `table`, the browser will try to be smart and render this:

``` html
<table v-component="my-table">
  <tbody>
    <tr>
      <td>{{test}}</td>
    </tr>
  </tbody>
</table>
```

The while `tbody` will then be transcluded into your `tr` in the component template. Which obviously is not ideal.

In general, it's hard to make transcluding table elements work properly, and I don't really see the benefits of doing so. In most cases you probably want to just pass down the data and let the component handle the rendering.
