### ISSUE TITLE
Is it possible to bind some of the component's fields while letting others be inlined with paramAttributes?

### ISSUE THREAD

**Issue by germansokolov13** [yyx990803/vue#698]
I've made a component as an encapsulation of using a plugin over a `textarea` tag. The component initializes the plugin when created and clears it when deleted. So it would be nice to use it like this:
`<my-textarea name="param"></my-textarea>`
Thus `name` should be declared in `paramAttributes`. But I also need my Vue instance containing such components to somehow react on changes of data when user types something in this textarea. Currently I can do it using `v-with` in nonspecific form but that way I won't be able to use `paramAttributes`.
Is there a way to solve this problem? Why can't `v-with: childMsg : parentMsg` update parentMsg when childMsg changes?

**Comment by TMiguelT** [comment]
As far as I know, no you can't make input components because of limitations of Vue. I made a thread about it on the discussion but I haven't heard anything yet: https://github.com/vuejs/Discussion/issues/120

**Comment by yyx990803** [comment]
As of 0.11.5 v-with is now two-way.

**Comment by shoshi** [comment]
Is it possible to make a `v-with` optionally one-way again? Is there a new one-way directive alternative? Or maybe I'm missing some way to parse the `parentMsg` as a string literal within `v-with`.

**Comment by germansokolov13** [comment]
@shoshi , did you try using `paramAttributes` as mentioned in the starting post? It is one-way still if I am not mistaken. Also, could you describe your usecase?

**Comment by shoshi** [comment]
@germansokolov13 Yes, `paramAttributes` do work.

Here's my quick oversimplified gist of our use case: http://jsfiddle.net/2sdrryss/2/ . Basically the main Vue makes a GET (#index) request to an API, which among many other things, sets the type of modal that should load. Then, the modal sets that template as a subcomponent and makes another GET (#show) request to load in more modal data.

I was hoping there was another `v-*` directive that might accomplish this. I guess it's more of a semantic argument. Since most of our other Vue tags start with `v-*` it makes sense that all attrs not normally present in html would be prefixed like that. For attrs like `src` and `width`, `paramAttributes` make perfect sense. For custom attrs, it's just be nice to have an option to prefix them in some way, making them look obviously different from normal html attrs.

**Comment by shoshi** [comment]
Nevermind, the issue is still present. Because I need to pass in `data` from the parent Vue into the component, it needs mustaches. With mustaches, the data becomes two-way bound again. http://jsfiddle.net/2sdrryss/3/ See line 30 of the coffeescript. On close, we change the `modalView` of the component, which then changes the `modalViewType` data on the parent Vue.

**Comment by shoshi** [comment]
Strangely enough, this is not an issue with camel case attrs `modalView` vs dashed attrs `modal-view`. However, not using dashes prompts the error: "[Vue warn]: You seem to be using camelCase for a paramAttribute, but HTML doesn't differentiate between upper and lower case. You should use hyphen-delimited attribute names. For more info see http://vuejs.org/api/options.html#paramAttributes"

This seems like an actual bug.

**Comment by yyx990803** [comment]
`paramAttributes` is just syntactic sugar for `v-with` - they are both two-way now.
I don't really understand why you'd want change the child's `modalView` on close, but if you don't want the child's view change to affect parent you can simply make a local copy of it in the compiled hook:

``` js
// child modal
compiled: function () {
  this.$set('localModalView', this.modalView)
}
```

**Comment by shoshi** [comment]
Using `close` was an oversimplification, and I can see that it seems a bit odd. Really the contents of the modal contain a button. Clicking the button makes an ajax call. If that call succeeds, the modalView changes to a success state which is another subcomponent of the child view. There are other subcomponents too for other conditions. Thus, you don't want to update the parent `modalViewType` every time the child `modalView` changes based on new data. While I could set an extra var that doesn't change like you suggested, it'd be nice not to have to overcomplicate it by adding more stuff. All I need to do is pass in the value once. Also, the browser doesn't need to spend any extra resources waiting for changes that will never occur. (Though I'm not sure how much this matters in Vue. I know it makes a difference in Angular.)

On Angular directives, having multiple options on scope is really useful:
```js
scope: {
  text:       "@justText",
  twoWayBind: "=twoWayBound",
  oneWayBind: "&oneWayBound"
}
```

I'm sure your goal is to keep Vue light, and I think that's great! That's why I chose Vue over Angular for this project. Is it possible that one-way binding could make it into a future version? Would this fit within your vision for Vue? Is there still some other architectural option I'm missing?

Thanks for all of your hard work on creating, maintaining, and updating Vue! It's truly fantastic.
