### ISSUE TITLE
VM dom elements (v-el) are undefined in transitions

### ISSUE THREAD

**Issue by kewah** [yyx990803/vue#713]
Hi,

I can't have access to vm DOM elements (ex: `this.$$.foo`) in transitions.
It's pretty useful to use them rather than having to select the element from the DOM (`el` param).

Here is a fiddle http://jsfiddle.net/kewah/an0fxwwg/
You can click on the window to toggle the child. I log `this.$$.foo` value in the console.

Thanks.

**Comment by yyx990803** [comment]
This is actually because the transition is triggered via `v-show`, which is a directive that belongs to the parent, so the `this` context in transition functions points to the parent instance. If you move the `v-show` into the child then it works as expected.

Maybe it's less confusing to always call transition functions on the instance bound to the element being animated (if there is one). It's a pretty simple change. Thoughts? @ayamflow

**Comment by yyx990803** [comment]
In 67eb247 a transition function' `this` context is set to the element's closest vm instance - which means if the element is the root node of an instance, that instance will be used as `this` context regardless of whether the transition is triggered by a parent directive or not.

**Comment by ayamflow** [comment]
Yes, I thought the `this` in transitions methods was set to the current VM. I guess that is expected behavior: it's the target of the transition. Thanks for the change! :+1:
