### ISSUE TITLE
Strange error, when we watch and work with the list.

### ISSUE THREAD

**Issue by grimalschi** [yyx990803/vue#728]
Demo: http://jsfiddle.net/e9e2bw6v/2/

We have list, which is under watching. In watch we just replace text:null to text: 'some text'.

When we add an item, and later we clear list, we see error.

We have html:
`<div v-if="list.length">`
`    <div v-if="list[0].text">`
`        {{list[0].text}}`
`    </div>`
`</div>`

If we remove second condition, we will not have error.

If you replace 2 conditions to 1 `<div v-if="list.length && list[0].text">`, we will not have error.

I cannot explain this, but its wrong.

P.S. Sory for bad english.

**Comment by grimalschi** [comment]
I found another way to get this error - after add item we run timeout, and in timeout we set value.

After cleaning list we will see error.

Demo: http://jsfiddle.net/4peaumas/1/

**Comment by grimalschi** [comment]
Note: if we change default value from "text: null" to "text: 'default'", it will be work well.

**Comment by TMiguelT** [comment]
I guess to summarize the problem for anyone else, when the list is cleared, **both** of the `v-if` conditions are now false (`list.length` and `list[0].text`). However the inner condition is still executed (resulting in an error) even though it should have been ignored due to the outer condition evaluating to false. 

So it looks like `v-if`s should be evaluated hierachically instead of in the order they are evaluated now.
