### ISSUE TITLE
Every Vue is inserted inside a new div?

### ISSUE THREAD

**Issue by slifszyc** [yyx990803/vue#744]
This is my code

```
var Vue = require('vue');

var Title = Vue.extend({
  template: '<h1>{{title}}</h1>'
});

var title = new Title({
  data: {
    title: 'Awesome title'
  }
})

title.$appendTo('.site-content');
```

Expected:
```
<section class="site-content">
  <h1>Awesome title</h1>
</section>
```

But I got:
```
<section class="site-content"><div><h1>Awesome title</h1></div></section>
```

And that happens with every Vue.
How can I avoid that `<div></div>` created to contain my template? Am I missing something?

Thanks!

**Comment by arthurmuchir** [comment]
I think you need to specify the 'el' option (in your case el: '.site-content'), as described here : http://vuejs.org/api/options.html#el

**Comment by yyx990803** [comment]
I assume you are using an older version of Vue, because in 0.11 the code would not work. In 0.11 if you don't provide the `el` option, your vm instance will be in **unmounted state**, you'd have to call `$mount()` instead of `$appendTo()`:

``` js
var Vue = require('vue');

var Title = Vue.extend({
  template: '<h1>{{title}}</h1>'
});

var title = new Title({
  data: {
    title: 'Awesome title'
  }
})

title.$mount('.site-content'); // use div.site-content as your root node
```

Some references:
http://vuejs.org/api/options.html#el
http://vuejs.org/api/instance-methods.html#vm-\$mount\(_\[element\|selector\]_\)
