### ISSUE TITLE
Price of instantiating a new Vue on every route in SPA?

### ISSUE THREAD

**Issue by suprMax** [yyx990803/vue#754]
Hi! I'm about to embark on a quest of building an admin panel, and I wanted to use Vue for it.

This is what I came up with: https://github.com/suprMax/vue-structure/tree/master/app/client

Can someone please tell me if I'm doing it "the right way"™?

I'm concerned about a price of re-creating entire "Vue" per route, but I couldn't figure a more elegant way that would avoid using components and weird requires in separate places.

Also this bit: https://github.com/suprMax/vue-structure/blob/master/app/client/base/router.coffee#L41

Should I call `.$destroy()` on each vue instance in this case?

**Comment by yyx990803** [comment]
There is no "the right way" in terms of routing for Vue, since that is not really in the scope of the framework and it depends on your app needs.

In most cases, re-creating a Vue instance should be fine, since unless your page consists of thousands of child instances it should render fast enough from the UX perspective. If you want, you can cache an already instantiated Vue instance and just remove it from the DOM instead of $destroying it, and later when the route is activated again, simply re-append it. This also has the benefits of persisted state, if needed.

**Comment by suprMax** [comment]
Got it! Thanks!

**Comment by boussou** [comment]
beware that if you use this combined with jquery, you will end up with memory leaks

**Comment by suprMax** [comment]
@boussou what do you mean?
