### ISSUE TITLE
the detached events not trigger

### ISSUE THREAD

**Issue by TerenceZ** [yyx990803/vue#801]
In the followed situations, some expected detached event(s) not fire:

1. `[v-if] > [v-repeat] > [template] > [v-component]`: In this structure, if we make `[v-if]` false after dynamic adding more components, the detached event won't be fired on the added components.  [demo](http://jsfiddle.net/TerenceZ/pgvjs8zw/4/)

2. `[v-repeat] > [template] > [v-component]`: In this structure, if reduce the repeat items, it will destroy the redundant components. However it seems that it clears all detached events in `_events` before firing for the redundant components. It's worth noting that there are no problems for  deeper components. [demo](http://jsfiddle.net/TerenceZ/mxo8x04f/4/)

Test version: 0.11.5 ~ 0.11.7.

**Comment by yyx990803** [comment]
Case 1 has been fixed in the `transclude-refactor` branch.

Case 2 is a bit different, because `v-events` and `events` option both only works when the instance is still active. When you set `total=0`, all instances are destroyed and the event listeners also. This also means it's not recommended to use the event system to listen to the internal lifecycle hooks.

**Comment by TerenceZ** [comment]
Oh, I think it also means the component may be cleared when invoking the internal detached event. If so, it's worth documenting these in the guide.

**Comment by yyx990803** [comment]
Closing (no actionable item regarding codebase)
