### ISSUE TITLE
How to make v-model synced while jQuery UI changing values?

### ISSUE THREAD

**Issue by danielchou** [yyx990803/vue#812]
Hi,
Sorry, I have posted the same question on Discussion repeatedly, thought maybe no one see this.

I have a form with date input bind with v-model and build with jQuery UI datepicker. So far I can get this value and pass through the model, please see [example](http://jsbin.com/xuyiva/2/edit?html,js,console,output), however, I do not prefer the way directly pass value. I see Vue 0.11.6 now supporting the jQuery event, could someone have a better way to handle this?

**Comment by yyx990803** [comment]
Here's an example wrapping it inside a custom directive: http://jsbin.com/yorosaneko/1/edit?html,js,console,output

**Comment by danielchou** [comment]
@yyx990803  Evan, thank you very much! :100:

I wish vue will have more examples, so that people could see its beauty and simplicity.

**Comment by swift1** [comment]
Nice solution and and epic example on using custom directives! Only one comment though:
onSelect should probably replaced with onClose, because when you use onSelect, the date value will only be updated when you click on a date, and not when you type in a date manually and then tab out of the input field.

**Comment by swift1** [comment]
Another truly epic thing is that the date picker directive can be encapsulated inside a component, like this:
````javascript
Vue.component('custom-component', {
	
	directives: {
		datepicker: {
			....
		}
	},	
	....
});
````
Gotta love Vue.js :smile:

**Comment by boovad** [comment]
AWESOME! :+1:

**Comment by maxKimoby** [comment]
Thank you so much! Another great feature developed by Vue team.

**Comment by brainless81** [comment]
Be careful using bootstrap-datepicker with this attempt. Using their changeDate event will lead to an endless loop! Could not figure out how to resolve that so I need to change to jquery's datepicker implementation.

**Comment by LKDevelopment** [comment]
@yyx990803 how is that possible in vuejs ? I've tried with the sample above and got the Datepicker displayed... but it doesn't set the data in the underlying model

**Comment by LinusBorg** [comment]
Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
