### ISSUE TITLE
`$el` from a component in a `v-repeat` is the `v-start` comment

### ISSUE THREAD

**Issue by sjoerdvisscher** [yyx990803/vue#821]
I just updated to vue v0.11.9 and got an error that the `$el` property of a component that is used in a `v-repeat` was the `v-start` comment node instead of its element. Reverting back to v0.11.8 fixed the issue.

Perhaps you know straight away what the issue is, if not, I'll try to make a minimal testcase.

**Comment by yyx990803** [comment]
Are you accessing `$el` directly, or was this error thrown by Vue internally? If the latter, I'd appreciate a jsfiddle.

**Comment by sjoerdvisscher** [comment]
Directly indeed.

**Comment by yyx990803** [comment]
So you are probably using a component with more than 1 top-level elements and `replace: true`. This will result in a "block instance" that basically manages a block of nodes defined by a v-start comment node and a v-end comment node. Previously a block instance's `$el` points to the first top-level element, and now it points to the `v-start` comment node. In this case I'm curious what you are trying to do with the `$el` of the block instance, since conceptually it doesn't have a root node.

**Comment by sjoerdvisscher** [comment]
Ah, you are completely right! A popup element got moved out of the root element because of z-index issues, and with 0.11.8 this kept working, so we never noticed that of course it shouldn't work! Thanks!
