### ISSUE TITLE
Can not set paramAttributes value in component initialization?

### ISSUE THREAD

**Issue by zhongqf** [yyx990803/vue#830]
consider this requirement:

have a avatar component, which accepts a `user` or `user-id` param.
if `user` is specified, use `user` object directly, otherwise retrieve user object by `user-id`.

my code is at: http://jsfiddle.net/xefvfsgy/3/

the problem is:
it seems that you can not set paramAttributes value in component initialization.

maybe using a computed attribute will solve this requirement, but I'm wondering what's wrong with the code above?

**Comment by yyx990803** [comment]
This is because the component data didn't have a `user` field, thus when you set `this.user = ...` it doesn't trigger an update. I think it does make sense to by default make all paramAttributes observed. In the meanwhile you can around this by using `this.$set('user', ...)`: http://jsfiddle.net/xefvfsgy/5/

**Comment by zhongqf** [comment]
Great, solved. 3x

" I think it does make sense to by default make all paramAttributes observed "
> I think it is really good and necessary. In api document, about paramAttributes, it's noted as 
================
An array of attribute names to be set on the Vue instance as initial data. Useful when passing data to a component.
================
It seems that `paramAttributes` is equal to `data` options, in my poor english.
