### ISSUE TITLE
Using v-with and paramAttributes

### ISSUE THREAD

**Issue by slaskis** [yyx990803/vue#837]
When I use `v-with` along with `paramAttributes` the param attributes are ignored. It seems like it doesn't merge those attributes into the v-with object.

I've narrowed it down to this minimal app:

```html
<div id="app">
    <div v-component='foo' use-link="true"></div>
    <div v-component='foo' v-with="obj1" use-link="true"></div>
    <div v-component='foo' v-with="obj2, useLink: false"></div>
</div>
```

```js
var app = new Vue({
    el: '#app',
    data: {
        obj1: {name: 'bula-1'},
        obj2: {name: 'bula-2'}
    },
    components: {
        "foo": {
            data: function() {
                return {
                    name: 'none'  
                };
            },
            paramAttributes: ['use-link'],
            template: '<div>{{name}} - {{useLink}}</div>',
        }
    }
});
```

Which can also be found as a jsfiddle: http://jsfiddle.net/r2yhcp1y/

What I'm expecting is a result of:

```
none - true
bula-1 - true
bula-2 - false
```

but instead it says:

```
none - true
bula-1 - 
bula-2 - false
```

Where the `useLink` param is simply ignored.

**Comment by yyx990803** [comment]
It is not recommended to mix full-data replace with single-prop `v-with`s, because you are essentially mutating the object passed down to the component with additional properties. It is better to just pass down the object as another property.

In 0.12 `v-with` is getting removed, and full-data replace will also no longer be supported.
