### ISSUE TITLE
paramAttributes with unobserved data and v-model

### ISSUE THREAD

**Issue by holic** [yyx990803/vue#843]
I'm trying to use `paramAttributes` with an expression that references a potentially unobserved data property on the parent object. I would like to pass a `value` attribute to my component that represents the value to be bound with `v-model`.

As you can see in the JSFiddle example below, the `title` property works just fine (as it's already defined on the `entry`), but the other fields don't have any effect on the on the `entry`. Is this intended behavior?

http://jsfiddle.net/nrru7obq/

```js
new Vue({
    el: document.body,
    template: '<div v-repeat="fields">{{ type }}: <div v-component="{{ type }}" value="{{ entry[prop] }}"></div></div><hr><pre>{{ entry | json }}</pre>',
    data: {
        entry: {
            title: 'hello world'
        },
        fields: [{
            type: 'text',
            prop: 'title'
        }, {
            type: 'text',
            prop: 'author'
        }, {
            type: 'textarea',
            prop: 'body'
        }]
    },
    components: {
        text: {
            replace: true,
            paramAttributes: ['value'],
            template: '<input type="text" v-model="value">'
        },
        textarea: {
            replace: true,
            paramAttributes: ['value'],
            template: '<textarea v-model="value"></textarea>'
        }
    }
})
```

(and same with `v-with`: http://jsfiddle.net/nrru7obq/1/)

**Comment by yyx990803** [comment]
This is because you are doing a two-way binding using a dynamic expression: `entry[prop]` cannot be parsed as a static path (a segment of the path is a variable), thus Vue can only generate a dynamic setter, which is basically `this.entry[this.prop] = ...`, which doesn't call `$add` if `this.prop` property doesn't already exist. In comparison, a static path generates a setter which can loop through the path segments and call `$add` if the key doesn't exist already.

In this case, it's probably necessary to ensure all fields are observed by manually calling `$add` for each field.

**Comment by holic** [comment]
@yyx990803 Since `$set` is now available on observed objects, would it be possible to use that in place of `$add`/directly setting the path to enable the use of dynamic expressions?

**Comment by yyx990803** [comment]
This would require non-trivial changes to the current path parser. Not sure if the use case is worth that effort, at least for now.

**Comment by holic** [comment]
No worries! I was mostly just curious as I'm not familiar with the internals.

Feel free to close this if this isn't something you plan to implement any time soon.
