### ISSUE TITLE
Can't get v-transition to work on nested v-repeat with array or object

### ISSUE THREAD

**Issue by OEvgeny** [yyx990803/vue#852]
When repeating repeated array/object properties transitions seems not work.
With 0.12 and array: http://jsfiddle.net/wh3tLgvn/26/
With 0.11 and object: http://jsfiddle.net/wh3tLgvn/17/
Press add colors button to show the issue.

**Comment by yyx990803** [comment]
In the `addColors` method you have this line:

``` js
this.colors.$set(this.curCategory, colors.concat(curColors))
```

The result of this triggers a diff for the outer repeat (because `this.colors` was mutated via `$set`). And during the diff, because you are setting that index to a new Array (result of `colors.concat(curColors)`), the diff algorithm thinks they are different and does a full re-render, thus no transitions are triggered.

One option here is to simply mutate the current child array:

``` js
curColors.unshift.apply(curColors, colors)
```

This only triggers an update for the inner repeat but not the outer one, and transitions would work as expected.

Note that this approach does not trigger update for your compare repeat below (the one using `v-repeat="colors[0]"`), because index access `[0]` does not register a dependency and the expression `colors[0]` only tracks the mutation of `this.colors`.

**Comment by OEvgeny** [comment]
Ah thanks very much. It was unclear, because part of my code worked well as I thought. 
Love Vue at all.
