### ISSUE TITLE
object.observe

### ISSUE THREAD

**Issue by paulpflug** [yyx990803/vue#903]
Hi,

I think `vue` is a great piece of code, although I can't use it currently. I was trying to use it within [atom](https://atom.io). The point is, using eval is forbidden, on the other hand `object.observe` is supported.

So I ask, do you plan to support `object.observe` ? maybe hidden behind a flag or by replacing a function at runtime like [rivets](http://rivetsjs.com/docs/guide/#adapters) does it?

I would be willing to help, if I'm able to.. I looked into the code, but the getter/setter generation seems pretty entangled in everything?

thanks

**Comment by yyx990803** [comment]
There's a `csp` branch which does not rely on `eval` and can be used in CSP enforcing environments, but the observation mechanism has nothing to do with `eval`.

At this moment supporting Object.observe is really not a high priority, because Chrome/Chromium is still the only environment that supports it, and it requires some pretty heavy changes to be made. I don't think I'll do that until the spec reaches stage 3/4 and other browsers start to implement it.

**Comment by lepture** [comment]
@yyx990803 brilliant choice.

**Comment by hbrls** [comment]
lol

**Comment by fnlctrl** [comment]
brilliant choice +1
https://mail.mozilla.org/pipermail/es-discuss/2015-November/044684.html

**Comment by plunntic** [comment]
It's also worth to say that object observe is going to be removed from chrome in version 50 and probably the ecma spec proposal too, see [Object.observe() implementation status](https://www.chromestatus.com/features/6147094632988672).
