### ISSUE TITLE
v-repeat doesn't remove elements on change

### ISSUE THREAD

**Issue by alchen** [yyx990803/vue#909]
JSFiddle: http://jsfiddle.net/alchen/rjqt2x91/4/
The fiddle does **not** show the problem, but it approximates what I'm doing. After clicking populate, it will show a list of values in three sections: left, center, and right (where `left` and `right` are arrays). 

The problem is that items in the array will stay in display and do not get removed, while listeners on the elements do get stripped away. It looks something like this:

```
Old Array: [1,2] => Displays: [1,2]
New Array: [1,2,3] => Displays: [1,2,3,1,2]
```

I found two changes that can help with the issue:
1. Remove `v-transition` on the `v-repeat` then the issue disappears.
2. In 5aa5c11, line 128 to 140 was removed from `src/directives/repeat.js`. If I just restore those lines into `repeat.js`, then the problem also goes away. (`translcude` and `compile` will need a couple of small changes into `compiler.transclude` and `compiler.compile`)

**Comment by yyx990803** [comment]
Have you tried updating to latest `dev`?

**Comment by alchen** [comment]
@yyx990803 Yes, I updated again after the comment, but that unfortunately didn't help. I'm still trying to figure out what's missing in the fiddle to reproduce the problem.

**Comment by alchen** [comment]
Okay, I think I finally got this reproduced: http://jsfiddle.net/alchen/rjqt2x91/7/
Steps to reproduce:
1. Click on one of the number in the list.
2. Quickly and repeatedly click on the first number of the second list.
3. The second list will grow in length with repeated elements.

Three factors contributes to this problem:
1. The outer component has `transition`.
2. The inner component uses `replace: true`.
3. The inner component uses css transition.

A new fix that I found:
- Implement `leave` function in the transition with a simple call to `done()`.

**Comment by yyx990803** [comment]
This is because you have applied a CSS animation on `.container`, and `.container` also is using `v-transition`. When Vue is running the transition, it detects the element has CSS animation on it, so Vue assumes you want to trigger a transition based on CSS animations, so it will listen for the "animationend" event to determine when the transition ends. However in your case, there's no leave animation, so the leave transition never finishes. Providing an explicit leave `done` callback fixes the problem.

I think this an unexpected side effect of the new mixed CSS/JS transition mode - maybe we need to allow a js transition to indicate `css: false` so that it knows it is a pure JavaScript transition and does not try to detect CSS properties.

**Comment by yyx990803** [comment]
I've added that in `dev`, now if you give your `keepScroll` transition `css: false`, things should work properly.

**Comment by alchen** [comment]
Okay, makes sense. I didn't think of CSS animations having anything to do with this, so it took a little longer to reproduce.

---

That was fast. Thanks for the updates! I think it'll also be nice to either give a warning or simply require both transitions to be present, because if this happens `css: false` wouldn't be the first thing I'd think of searching.

**Comment by yyx990803** [comment]
It should be more obvious after reading the updated transition docs for 0.12 - but it is not out yet ;)
