### ISSUE TITLE
filter can't sync <select> value

### ISSUE THREAD

**Issue by green-mike** [yyx990803/vue#913]
hi, when I used filter change select's value, the option still stay at selected value. But the input text is right. I try to trigger select 'change' or 'input' but doesn't work, how can I fix it ?

http://jsfiddle.net/mike_huang/htpka9gj/1/

how can I fix it?

**Comment by yyx990803** [comment]
This is a kinda unusual use case...
Instead of using a write filter you should probably just use a watcher.
Since v-model locks itself when writing to the model, you need to use `Vue.nextTick` to wait until it unlocks so that the overwrite can affect the select v-model: http://jsfiddle.net/htpka9gj/2/

**Comment by green-mike** [comment]
thanks a lot for your help!!
