### ISSUE TITLE
Restore v-component for lists

### ISSUE THREAD

**Issue by damienfournier** [yyx990803/vue#941]
Hi,

I was prototyping an app with vue and nestedsortable (https://github.com/ilikenwf/nestedSortable)

It was working with vue 0.11
http://jsfiddle.net/0vjec2h4/3/
(nb: this demo works with Firefox & Opera, but not with Chrome or IE)

But with vue 0.12 and the end of v-component, I haven't succeeded in porting that code. 
The nestedSortable library is not made to use custom components, and there is always something not working in any variation that I tried.

So, would it be possible to make an exception for ul/ol/li elements to still have the v-component directive ? like the exception for table elements, in order to not break usage with jquery plugins that use list elements.

Thanks !

**Comment by yyx990803** [comment]
You can put the outer `li` into the component's template, and then use `replace: true` so that the custom element will be replaced with the `li`.

One additional note: the following line

``` js
var id = ui.item[0].firstChild.attributes[0].value;
```

needs to be changed to:

``` js
var id = ui.item[0].children[0].attributes[0].value;
```

Because the `firstChild` can be an empty textNode. You want to make sure you are accessing the first element child.

Fixed example: http://jsfiddle.net/0vjec2h4/4/

**Comment by damienfournier** [comment]
Wow... great !

many thanks ! you're the best !
