### ISSUE TITLE
Bring v-component back because of `prefix` being configurable

### ISSUE THREAD

**Issue by BigBlueHat** [yyx990803/vue#963]
I just noticed this line in the [0.12.0 release notes](https://github.com/yyx990803/vue/releases/tag/0.12.0):
> v-component has been removed. Now all components should use the custom tag syntax. For dynamic components, a new syntax is introduced: <component type="{{view}}"></component>.

I've only just today switched [the CMS I'm building with Vue.js](http://github.com/bigbluehat/blueink) to "wrap" Vue.js (by renaming it on require) and setting up a custom prefix:
https://github.com/BigBlueHat/BlueInk/commit/752c6de30b236b8e2677d7a7cb5b8a63f013ccfb
specifically:
https://github.com/BigBlueHat/BlueInk/blob/752c6de30b236b8e2677d7a7cb5b8a63f013ccfb/src/main.js#L4-L7

When I made that change I had to move away from using `<custom-element>` syntax because the site I'm building also uses Vue.js and that Vue would be the one to catch the custom elements rather than the re-named one--race condition, I'd reckon.

If `v-component` goes a way entirely, I'm not sure how you could have two Vue.js' in play without the race condition.

Thoughts? :smile_cat:

**Comment by yyx990803** [comment]
So you are saying you will be compiling the same template with two versions of Vue? That doesn't sound like it would work properly.

**Comment by steffans** [comment]
I also like the `v-component` directive, because it is a nice way to turn any HTML element into a component dynamically. It was basically like the HTML5 custom element spec, were any element can be turned to a custom element using the `is` attribute.

**Vue 0.11**

```html
<ul>
    <li v-repeat="item: items" v-component="item.name" props="..."></li>
</ul>

<script>
    
    // item component pseudo code
    {
        template: '<div> my item ... </div>'        
    }
    
</script>
```
In v0.12 i need to do this in order to get the same result. This is because dynamic compnents only work as a tag `<component is="...">` not as a attribute like `v-component` did.

**Vue 0.12**

```html
<ul>
    <li v-repeat="item: items">
        <component is="item.name" props="..."></component>
    </li>
</ul>

<script>
    
    // item component pseudo code
    {
         replace: true, // needed to remove the <component>
         template: '<div> my item ... </div>'        
    }
    
</script>
```
Having a `v-component` directive makes dynamics components easier because you can apply them to existing elements and keep their semantics. 

```html
// good semantics
<ul>
    <li v-repeat="item: items" v-component="item.name" props="..."></li>
</ul>

// wrong semantics
<ul>
    <component v-repeat="item: items" is="item.name" props="..."></component>
</ul>
```

**Comment by Nirazul** [comment]
I'm not sure if I understand you correctly, but wouldn't the [replace option](http://vuejs.org/api/options.html#replace) solve this problem?

**Comment by yyx990803** [comment]
@steffans in 0.12.2 the plan is to default `replace` to `true`, so you can always include the correct semantic element to use in your component template.

That does leave you with the case where the raw template looks like this:

``` html
<ul>
    <component v-repeat="item: items" is="item.name" props="..."></component>
</ul>
```

But the rendered result would be semantically correct.

**Comment by Lidbetter** [comment]
In a recent commit the replace option is the default (probably to combat this exact problem)

The only other thing to note, is that it is less obvious what `<component> </component>` actually is, without digging into the template you are using for that component.

Which doesn't seem like a huge problem, but knowing the html element type (for styling etc.) is more useful

**Comment by steffans** [comment]
@yyx990803 In your example the `<li>` tag would need to be added to the component template.

```html
<ul>
    <component v-repeat="item: items" is="item.name" props="..."></component>
</ul>

<script>
    
    // item component pseudo code
    {
        template: '<li><div> my item ... </div></li>'        
    }
    
</script>
```

I actually liked the  `v-component` directive, because the behavior is the exactly same as using HTML5 custom elements. They don't replace the element itself, they extend/enhance it in a way. A replacement is optional and not needed most of the times. 

**HTML5 Web Component**
http://www.html5rocks.com/en/tutorials/webcomponents/customelements/#instantiating
```html
<button is="mega-button"></button>
```

**Vue Component (v0.12)**
The default replace `true` could be somehow confusing, because the `<button>` element has to be always part of the template.
```html
<component is="mega-button"></component>

<script>
    
    {
         // auto replace true (implicit)
        template: '<button>My mega button</button>'  // recreate button element
    }
    
</script>
```

**Vue Directive**
I would actually never use the new `<component is="mega-button">` syntax because the directive look nicer.
```html
// works in v0.11
<button v-component="mega-button"></button> 

// maybe this is nicer ;-)
<button v-is="mega-button"></button> 
```

**Comment by thelinuxlich** [comment]
I disagree, your proposal adds the need to know exactly which element type mega-button is targeting, not good :-1:

**Comment by yyx990803** [comment]
@steffans why don't you just use `<mega-button></mega-button>`?

**Comment by yyx990803** [comment]
Post 0.12.2 (after `replace` default to true), the recommended usage would be:

- Always include the root element in your component template
- Use custom element component whenever possible
- Only use `<component is="{{}}">` for dynamic components
- Only use `v-component` on table elements

But I guess relaxing the restriction a bit doesn't hurt if you have a strong preference on the style =/

**Comment by steffans** [comment]
@yyx990803 Yes `<mega-button></mega-button>` would be the first choice, for me as well. My previous comments were mainly about using it as a dynamic component. Because in this case a applying a directive to an existing element seems easier to me, then creating a generic tag with `<component is="{{}}">` :relaxed:

**Comment by BigBlueHat** [comment]
Keeping a configurable prefixed `v-component` around should do the trick for my purposes--so I'd be appreciative. :smile:

**Comment by miljan-aleksic** [comment]
I vote for ```<button v-is="mega-button"></button> ```, it's shorter than v-component, is same as in HTML5, works with tables and provide flexibility when replacing and when not.

**Comment by thelinuxlich** [comment]
I fail to see the advantage of having to know that, to use "mega-button" component, I need to know that it requires a button tag :P

**Comment by steffans** [comment]
@thelinuxlich Normally the custom element `<mega-button></mega-button>` should be used whenever possible. However when using the `v-component` directive it's actually intended to apply this component to a certain tag like a `<button>`. Further this way a component could work with multiple tags. Always considered that the replace option is disabled, if not the current would be replaced anyway :wink:

**Comment by yyx990803** [comment]
I've relaxed the limitation on `v-component` - since it is still useful for table/svg elements in some cases, and does provide the "same component, different element type" functionality. I'm not changing it to `v-is` because it could get confusing with `<component is="...">` , and is at the same time a breaking change.

**Comment by airtonix** [comment]
Loss of the {{v-component}} attribute now means Vue.Js is no longer feasiable for sites requiring SEO.

In other words I can no longer create a progressively enhanced site.

directives are not good enough (can't use events or methods properly)

**Comment by yyx990803** [comment]
@airtonix The equivalent for v-component in 1.0 is the [is attribute](http://vuejs.org/guide/components.html#is_attribute).

Also, not sure why it has anything to do with SEO. In the final rendered markup custom elements are replaced by the root element in your template.

**Comment by BigBlueHat** [comment]
@yyx990803 so... `Vue.config.prefix` seems to be gone...

Is there anyway to simulate that? It was previously possible to have 2 Vue's within a single page--even different versions. It doesn't seem that would be possible any longer, so a CMS (such as mine) using Vue.js for it's UI would force any web site hosted within it to also upgrade to that version of Vue.js.

Is that avoidable? It used to be.

Thanks!

**Comment by BigBlueHat** [comment]
Here's the commit:
https://github.com/vuejs/vue/commit/5b9759c185318ef8749d5231dc85640b2bb885ee

**Comment by yyx990803** [comment]
@BigBlueHat if you have two copies of Vue compiling the same piece of DOM, unfortunately that is no longer possible. It just adds a lot of extra complexity to Vue's compiler for marginal benefits.

However, you can use `v-pre` in one Vue to completely skip a sub DOM tree, which can then be compiled using another Vue copy.

**Comment by BigBlueHat** [comment]
Hrm...not sure that would work in this case as the content items within the page are themselves BlueInk components--such that the CMS can update them dynamically when they change, inject buttons for settings, editing, deleting, as well as enabling drag and drop around the page.

The web site also needs access to those DOM trees as its there content. :smile: 

I'll have to chew on this some more to see what options remain.

Thanks for the idea, though!

**Comment by airtonix** [comment]
@yyx990803 it's relevant to SEO because if the content of my page is only constructed after the response from the server by the browser, then google will not index any of that content.

Thanks for pointing out the `is` directive. combined with `replace: false` I am still able to take standard html5 tags and decorate them with attributes.

We're looking for a framework that can do full blown client-side applications and simple progressive enhancement. We're also adopting Atomic Design, so being able to put parts together in a child/parent relationship is important.

1. React doesn't do attributes, only tags and it destroys the content.
2. Angular has for a long time been adequate for my own personally strategy, but I now work in a team where others find it difficult to grok angular.
3. Backbone still relies on underscore
4. Knockout is `lol`

Vue.js (at the moment) provides our team with something simple to write code for, but with enough builtins that we potentially wouldn't need to write any JS to get simple concept flows working thanks to `v-if`, `v-show`, `v-on` etc.

But the most essential part of Vue.js is that I can write components as attributes that do not destroy the original markup.

**Comment by simplesmiler** [comment]
@airtonix you may also be interested in the `inline-template` feature if you are not yet :)
