### ISSUE TITLE
Repeat Component with Identifier

### ISSUE THREAD

**Issue by blackChef** [yyx990803/vue#992]
Vue.component('vue-item', {
      props: ['content'],
      replace: false,
      template: '<div v-text="content"></div>'
    });

    Vue.component('vue-list', {
      props: ['items'],
      replace: false,

      // didn't work
      template: '<vue-item v-repeat="item: items" content="{{item.content}}"></vue-item>'
    });

When I try to use identifier to pass value to child component through props, I get message: ` Error when evaluating expression "item.content"`.

**Comment by miljan-aleksic** [comment]
That seems wrong. Try with:

```
<vue-item v-repeat="items"></vue-item>
```

No need for props there as v-repeat will bind the data to the child on each iterance.

**Comment by blackChef** [comment]
@miljan-aleksic Yes, that'll work. `<vue-item v-repeat="items" content="{{content}}"></vue-item>` this will work too. But for the sake of consistancy, they should all work.

**Comment by yyx990803** [comment]
Read this: http://vuejs.org/guide/best-practices.html#Component_Scope

**Comment by yyx990803** [comment]
Please read this: http://vuejs.org/guide/best-practices.html#Component_Scope

The example doesn't work because it's a component, so the expression for the prop (`item.content`) is compiled in parent scope.

And in this case, a prop is not needed; you can simply access it as `item.content` inside your component.
