### ISSUE TITLE
wait-for and $emit do not work with dynamic component

### ISSUE THREAD

**Issue by desperate-man** [yyx990803/vue#999]
I have a main view model and I define a dynamic component inside of it, this component must be initialized with data before it gets rendered, e.g. ajax call. On the layout I insert "wait-for" attribute for the component element.
Initially on the component's "compiled" event I've tried to invoke $emit("data-loaded") immediately, without doing anything there and my component was never rendered and component's "ready" event wasn't invoked.
When I put a dummy "setTimeout" function inside "compiled" event and in the callback I invoke $emit("data-loaded") everything works fine, component is rendered. Here are two examples, not working http://jsfiddle.net/qf6ap0ga/3/ and working http://jsfiddle.net/qf6ap0ga/4/

**Comment by yyx990803** [comment]
This is expected behavior. When you add the `wait-for`, Vue assumes you are doing some async operations before emitting the event, otherwise there's no point in using `wait-for`. When you perform an ajax request, the result always comes back asynchronously. Emitting the event synchronously will have no effect.

**Comment by desperate-man** [comment]
Hm, now I know, thanks a lot!

**Comment by nkovacs** [comment]
I ran into this as well. The problem is that I have a dynamic component, where some components are async and some are not. But all of them have to emit the event to be rendered.
I worked around it by using nextTick.
There's also the issue that some things can be async in some cases and sync in others, e.g. a function that only gets data from the server if the client-side data is not yet available, and then caches it and calls the callback immediately next time.
